// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIU-mokn_1SIpuhvwYOsm8lZFitbTLkqA',
    appId: '1:589976622977:web:d07a8f7c8193bf5df33a80',
    messagingSenderId: '589976622977',
    projectId: 'vetra-20540',
    authDomain: 'vetra-20540.firebaseapp.com',
    storageBucket: 'vetra-20540.firebasestorage.app',
    measurementId: 'G-Z5ZDPXN2RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7aE4MOg6cd6gw9TucmEGC3ku7okdKTM',
    appId: '1:589976622977:android:48bfd53d492b23d1f33a80',
    messagingSenderId: '589976622977',
    projectId: 'vetra-20540',
    storageBucket: 'vetra-20540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR65Xx9koCTTqEbLYYhN5EjSjcyGJhgHI',
    appId: '1:589976622977:ios:09a4844fd7fec134f33a80',
    messagingSenderId: '589976622977',
    projectId: 'vetra-20540',
    storageBucket: 'vetra-20540.firebasestorage.app',
    iosBundleId: 'com.example.vetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR65Xx9koCTTqEbLYYhN5EjSjcyGJhgHI',
    appId: '1:589976622977:ios:09a4844fd7fec134f33a80',
    messagingSenderId: '589976622977',
    projectId: 'vetra-20540',
    storageBucket: 'vetra-20540.firebasestorage.app',
    iosBundleId: 'com.example.vetra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIU-mokn_1SIpuhvwYOsm8lZFitbTLkqA',
    appId: '1:589976622977:web:540e552202c1b38df33a80',
    messagingSenderId: '589976622977',
    projectId: 'vetra-20540',
    authDomain: 'vetra-20540.firebaseapp.com',
    storageBucket: 'vetra-20540.firebasestorage.app',
    measurementId: 'G-V69K12KFJK',
  );
}
