import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

import 'screens/landing_page.dart';
import 'screens/admin/admin_login_page.dart';
import 'screens/admin/admin_dashboard_screen.dart';
import 'screens/admin/admin_analytics_screen.dart';
import 'screens/admin/admin_users_screen.dart';
import 'screens/admin/broadcast_message_screen.dart';
import 'screens/users/user_login_page.dart';
import 'screens/users/user_signup_page.dart';
import 'screens/users/user_dashboard.dart';
import 'screens/users/notification_center_screen.dart';
import 'screens/users/team_chat_screen.dart';
import 'screens/users/leaderboard_screen.dart';
import 'screens/users/profile_customization_screen.dart';
import 'screens/users/help_support_screen.dart';
import 'utils/app_theme.dart';
import 'dart:async'; // for Timer

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'VETRA - Tournament Booking',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.getTheme(),
      initialRoute: '/splash',
      routes: {
        '/splash': (context) => const SplashScreen(),
        '/': (context) => const LandingPage(),
        '/admin-login': (context) => const AdminLoginPage(),
        '/admin-dashboard': (context) => const AdminDashboardScreen(),
        '/admin': (context) => const AdminDashboardScreen(),
        '/admin-analytics': (context) => const AdminAnalyticsScreen(),
        '/admin-users': (context) => const AdminUsersScreen(),
        '/admin-broadcast': (context) => const BroadcastMessageScreen(),
        '/user-login': (context) => const UserLoginPage(),
        '/user-signup': (context) => const UserSignupPage(),
        '/user-dashboard': (context) => const UserDashboardPage(),
        '/user-notifications': (context) => const NotificationCenterScreen(),
        '/user-team-chat': (context) => const TeamChatScreen(),
        '/user-leaderboard': (context) => const LeaderboardScreen(),
        '/user-profile': (context) => const ProfileCustomizationScreen(),
        '/user-help': (context) => const HelpSupportScreen(),
      },
      onUnknownRoute: (settings) {
        return MaterialPageRoute(builder: (context) => const LandingPage());
      },
    );
  }
}

// ================= Splash Screen =================

class SplashScreen extends StatefulWidget {
  const SplashScreen({Key? key}) : super(key: key);

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  String displayText = "";
  final String fullText = "Where Every Match Begins...";
  int charIndex = 0;

  @override
  void initState() {
    super.initState();

    // Typing animation
    Timer.periodic(const Duration(milliseconds: 150), (timer) {
      if (charIndex < fullText.length) {
        setState(() {
          displayText += fullText[charIndex];
          charIndex++;
        });
      } else {
        timer.cancel();
      }
    });

    // Navigate to LandingPage after 10 seconds
    Timer(const Duration(seconds: 5), () {
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (context) => const LandingPage()),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF6f42c1), // theme color
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // Rounded Logo
            ClipRRect(
              borderRadius: BorderRadius.circular(30),
              child: Image.asset(
                "assets/Vetra_logo.png", // replace with your logo path
                height: 120,
              ),
            ),
            const SizedBox(height: 20),
            const Text(
  "VETRA",
  textAlign: TextAlign.center,
  style: TextStyle(
    color: Colors.white,
    fontSize: 26,
    fontWeight: FontWeight.bold,
  ),
),

            const SizedBox(height: 15),
            // Typing animation text
            Text(
              displayText,
              style: const TextStyle(
                color: Colors.white70,
                fontSize: 18,
                fontStyle: FontStyle.italic,
              ),
            ),
          ],
        ),
      ),
    );
  }
}