// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

import 'screens/landing_page.dart';
import 'screens/admin/admin_login_page.dart';
import 'screens/admin/admin_dashboard_screen.dart';
import 'screens/users/user_login_page.dart';
import 'screens/users/user_signup_page.dart';
import 'screens/users/user_dashboard_screen.dart';
import 'screens/users/user_dashboard.dart';
import 'utils/app_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'VETRA - Tournament Booking',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.getTheme(),
      initialRoute: '/',
      routes: {
        '/': (context) => const LandingPage(),
        '/admin-login': (context) => const AdminLoginPage(),
        '/admin-dashboard': (context) => const AdminDashboardScreen(),
        '/admin': (context) => const AdminDashboardScreen(),
        '/user-login': (context) => const UserLoginPage(),
        '/user-signup': (context) => const UserSignupPage(),
        '/user-dashboard': (context) => const UserDashboardPage(),
        '/user': (context) => const UserDashboardScreen(),
      },
      onUnknownRoute: (settings) {
        return MaterialPageRoute(builder: (context) => const LandingPage());
      },
    );
  }
}
